// Copyright Nightona Platforms Inc.
// SPDX-License-Identifier: AGPL-3.0

package exporter

import (
	"github.com/Amartuvshins0404/nightona/libs/common-go/pkg/envcompat"
)

// The collector binary is generated by the OpenTelemetry Collector Builder,
// so there is no main() under our control. Aliasing legacy DAYTONA_* env vars
// in init() guarantees it runs before the collector resolves ${env:...}
// references in its configuration.
func init() {
	envcompat.ApplyLegacyEnvAliases()
}
